[tool.poetry]
name = "vae-prop"
version = "0.1.0"
description = ""
authors = ["Jiyan Schneider <jiyan.schneider@keio.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
nbdev = "^2.3.34"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
