# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vae_prop',
                'doc_host': 'https://jiyans.github.io',
                'git_url': 'https://github.com/jiyans/vae_prop',
                'lib_path': 'vae_prop'},
  'syms': {'vae_prop.core': {'vae_prop.core.foo': ('core.html#foo', 'vae_prop/core.py')}}}
